version: '3.7'
services:
  client:
    build:
      dockerfile: local.Dockerfile
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
  nginx:
    build:
      dockerfile: local.Dockerfile
      context: ./nginx
    ports:
      - 80:80
    restart: always
  postgres:
    image: 'postgres:12.1-alpine'
  redis:
    image: 'redis:5.0-alpine'
  api:
    build:
      dockerfile: local.Dockerfile
      context: ./server
    environment:
      - PGDATABASE=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - PGUSER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app
  worker:
    build:
      dockerfile: local.Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /home/node/app/node_modules
      - ./worker:/home/node/app
