// @flow
export const FETCH_INDEXES_FAIL = 'FETCH_INDEXES_FAIL';
export const FETCH_INDEXES_START = 'FETCH_INDEXES_START';
export const FETCH_INDEXES_SUCCESS = 'FETCH_INDEXES_SUCCESS';
export const FETCH_VALUES_FAIL = 'FETCH_VALUES_FAIL';
export const FETCH_VALUES_START = 'FETCH_VALUES_START';
export const FETCH_VALUES_SUCCESS = 'FETCH_VALUES_SUCCESS';
