// @flow
export const FETCH_INDEXES_FAIL = 'FETCH_INDEXES_FAIL';
export const FETCH_INDEXES_START = 'FETCH_INDEXES_START';
export const FETCH_INDEXES_SUCCESS = 'FETCH_INDEXES_SUCCESS';
export const FETCH_VALUE_FOR_INDEX_FAIL = 'FETCH_VALUE_FOR_INDEX_FAIL';
export const FETCH_VALUE_FOR_INDEX_START = 'FETCH_VALUE_FOR_INDEX_START';
export const FETCH_VALUE_FOR_INDEX_SUCCESS = 'FETCH_VALUE_FOR_INDEX_SUCCESS';
export const FETCH_VALUES_FAIL = 'FETCH_VALUES_FAIL';
export const FETCH_VALUES_START = 'FETCH_VALUES_START';
export const FETCH_VALUES_SUCCESS = 'FETCH_VALUES_SUCCESS';
export const SET_INDEX = 'SET_INDEX';
